//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtraType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExportProfile" type="{}ExportProfileType"/>
 *         &lt;element name="ExportRevision" type="{}ExportRevisionType"/>
 *         &lt;element name="StemExportProfile" type="{}StemExportProfileType"/>
 *         &lt;element name="UI" type="{}UIType"/>
 *         &lt;element name="Videomonitor" type="{}VideomonitorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtraType", propOrder = {
    "exportProfile",
    "exportRevision",
    "stemExportProfile",
    "ui",
    "videomonitor"
})
public class ExtraType {

    @XmlElement(name = "ExportProfile", required = true)
    protected ExportProfileType exportProfile;
    @XmlElement(name = "ExportRevision", required = true)
    protected ExportRevisionType exportRevision;
    @XmlElement(name = "StemExportProfile", required = true)
    protected StemExportProfileType stemExportProfile;
    @XmlElement(name = "UI", required = true)
    protected UIType ui;
    @XmlElement(name = "Videomonitor", required = true)
    protected VideomonitorType videomonitor;

    /**
     * Gets the value of the exportProfile property.
     * 
     * @return
     *     possible object is
     *     {@link ExportProfileType }
     *     
     */
    public ExportProfileType getExportProfile() {
        return exportProfile;
    }

    /**
     * Sets the value of the exportProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportProfileType }
     *     
     */
    public void setExportProfile(ExportProfileType value) {
        this.exportProfile = value;
    }

    /**
     * Gets the value of the exportRevision property.
     * 
     * @return
     *     possible object is
     *     {@link ExportRevisionType }
     *     
     */
    public ExportRevisionType getExportRevision() {
        return exportRevision;
    }

    /**
     * Sets the value of the exportRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportRevisionType }
     *     
     */
    public void setExportRevision(ExportRevisionType value) {
        this.exportRevision = value;
    }

    /**
     * Gets the value of the stemExportProfile property.
     * 
     * @return
     *     possible object is
     *     {@link StemExportProfileType }
     *     
     */
    public StemExportProfileType getStemExportProfile() {
        return stemExportProfile;
    }

    /**
     * Sets the value of the stemExportProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link StemExportProfileType }
     *     
     */
    public void setStemExportProfile(StemExportProfileType value) {
        this.stemExportProfile = value;
    }

    /**
     * Gets the value of the ui property.
     * 
     * @return
     *     possible object is
     *     {@link UIType }
     *     
     */
    public UIType getUI() {
        return ui;
    }

    /**
     * Sets the value of the ui property.
     * 
     * @param value
     *     allowed object is
     *     {@link UIType }
     *     
     */
    public void setUI(UIType value) {
        this.ui = value;
    }

    /**
     * Gets the value of the videomonitor property.
     * 
     * @return
     *     possible object is
     *     {@link VideomonitorType }
     *     
     */
    public VideomonitorType getVideomonitor() {
        return videomonitor;
    }

    /**
     * Sets the value of the videomonitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideomonitorType }
     *     
     */
    public void setVideomonitor(VideomonitorType value) {
        this.videomonitor = value;
    }

}
