//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FadeInType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FadeInType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AutomationList" type="{}AutomationListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FadeInType", propOrder = {
    "automationList"
})
public class FadeInType {

    @XmlElement(name = "AutomationList", required = true)
    protected AutomationListType automationList;

    /**
     * Gets the value of the automationList property.
     * 
     * @return
     *     possible object is
     *     {@link AutomationListType }
     *     
     */
    public AutomationListType getAutomationList() {
        return automationList;
    }

    /**
     * Sets the value of the automationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutomationListType }
     *     
     */
    public void setAutomationList(AutomationListType value) {
        this.automationList = value;
    }

}
