//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.codingspiderfox.ardoursessionparser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Session_QNAME = new QName("", "Session");
    private final static QName _RegionTypeInverseFadeIn_QNAME = new QName("", "InverseFadeIn");
    private final static QName _RegionTypeFadeIn_QNAME = new QName("", "FadeIn");
    private final static QName _RegionTypeFadeOut_QNAME = new QName("", "FadeOut");
    private final static QName _RegionTypeInverseFadeOut_QNAME = new QName("", "InverseFadeOut");
    private final static QName _RegionTypeEnvelope_QNAME = new QName("", "Envelope");
    private final static QName _PlaylistTypeRegion_QNAME = new QName("", "Region");
    private final static QName _ChannelTypePort_QNAME = new QName("", "Port");
    private final static QName _ProcessorTypePannable_QNAME = new QName("", "Pannable");
    private final static QName _ProcessorTypeOutputMap0_QNAME = new QName("", "OutputMap-0");
    private final static QName _ProcessorTypeAutomation_QNAME = new QName("", "Automation");
    private final static QName _ProcessorTypePresetOutput_QNAME = new QName("", "PresetOutput");
    private final static QName _ProcessorTypeControllable_QNAME = new QName("", "Controllable");
    private final static QName _ProcessorTypeThruMap_QNAME = new QName("", "ThruMap");
    private final static QName _ProcessorTypePannerShell_QNAME = new QName("", "PannerShell");
    private final static QName _ProcessorTypeCustomSinks_QNAME = new QName("", "CustomSinks");
    private final static QName _ProcessorTypeConfiguredOutput_QNAME = new QName("", "ConfiguredOutput");
    private final static QName _ProcessorTypeInputMap0_QNAME = new QName("", "InputMap-0");
    private final static QName _ProcessorTypeWindowsVst_QNAME = new QName("", "windows-vst");
    private final static QName _ProcessorTypeConfiguredInput_QNAME = new QName("", "ConfiguredInput");
    private final static QName _PortTypeConnection_QNAME = new QName("", "Connection");
    private final static QName _AutomationListTypeEvents_QNAME = new QName("", "events");
    private final static QName _InputMap0TypeChannelmap_QNAME = new QName("", "Channelmap");
    private final static QName _ObjectTypeObject_QNAME = new QName("", "Object");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.codingspiderfox.ardoursessionparser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RouteType }
     * 
     */
    public RouteType createRouteType() {
        return new RouteType();
    }

    /**
     * Create an instance of {@link SessionType }
     * 
     */
    public SessionType createSessionType() {
        return new SessionType();
    }

    /**
     * Create an instance of {@link RoutesType }
     * 
     */
    public RoutesType createRoutesType() {
        return new RoutesType();
    }

    /**
     * Create an instance of {@link LTCInType }
     * 
     */
    public LTCInType createLTCInType() {
        return new LTCInType();
    }

    /**
     * Create an instance of {@link DiskstreamType }
     * 
     */
    public DiskstreamType createDiskstreamType() {
        return new DiskstreamType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link InputMap0Type }
     * 
     */
    public InputMap0Type createInputMap0Type() {
        return new InputMap0Type();
    }

    /**
     * Create an instance of {@link LocationsType }
     * 
     */
    public LocationsType createLocationsType() {
        return new LocationsType();
    }

    /**
     * Create an instance of {@link ControllableType }
     * 
     */
    public ControllableType createControllableType() {
        return new ControllableType();
    }

    /**
     * Create an instance of {@link IOType }
     * 
     */
    public IOType createIOType() {
        return new IOType();
    }

    /**
     * Create an instance of {@link ClickType }
     * 
     */
    public ClickType createClickType() {
        return new ClickType();
    }

    /**
     * Create an instance of {@link ExtraType }
     * 
     */
    public ExtraType createExtraType() {
        return new ExtraType();
    }

    /**
     * Create an instance of {@link CustomSinksType }
     * 
     */
    public CustomSinksType createCustomSinksType() {
        return new CustomSinksType();
    }

    /**
     * Create an instance of {@link OutputMap0Type }
     * 
     */
    public OutputMap0Type createOutputMap0Type() {
        return new OutputMap0Type();
    }

    /**
     * Create an instance of {@link InverseFadeOutType }
     * 
     */
    public InverseFadeOutType createInverseFadeOutType() {
        return new InverseFadeOutType();
    }

    /**
     * Create an instance of {@link SourcesType }
     * 
     */
    public SourcesType createSourcesType() {
        return new SourcesType();
    }

    /**
     * Create an instance of {@link ExportFormatType }
     * 
     */
    public ExportFormatType createExportFormatType() {
        return new ExportFormatType();
    }

    /**
     * Create an instance of {@link RegionsType }
     * 
     */
    public RegionsType createRegionsType() {
        return new RegionsType();
    }

    /**
     * Create an instance of {@link ControlProtocolsType }
     * 
     */
    public ControlProtocolsType createControlProtocolsType() {
        return new ControlProtocolsType();
    }

    /**
     * Create an instance of {@link FolderType }
     * 
     */
    public FolderType createFolderType() {
        return new FolderType();
    }

    /**
     * Create an instance of {@link ConfiguredInputType }
     * 
     */
    public ConfiguredInputType createConfiguredInputType() {
        return new ConfiguredInputType();
    }

    /**
     * Create an instance of {@link SpeakerType }
     * 
     */
    public SpeakerType createSpeakerType() {
        return new SpeakerType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link ExportProfileType }
     * 
     */
    public ExportProfileType createExportProfileType() {
        return new ExportProfileType();
    }

    /**
     * Create an instance of {@link PresentationInfoType }
     * 
     */
    public PresentationInfoType createPresentationInfoType() {
        return new PresentationInfoType();
    }

    /**
     * Create an instance of {@link StemExportProfileType }
     * 
     */
    public StemExportProfileType createStemExportProfileType() {
        return new StemExportProfileType();
    }

    /**
     * Create an instance of {@link PlaylistType }
     * 
     */
    public PlaylistType createPlaylistType() {
        return new PlaylistType();
    }

    /**
     * Create an instance of {@link FadeInType }
     * 
     */
    public FadeInType createFadeInType() {
        return new FadeInType();
    }

    /**
     * Create an instance of {@link ChannelmapType }
     * 
     */
    public ChannelmapType createChannelmapType() {
        return new ChannelmapType();
    }

    /**
     * Create an instance of {@link AutomationType }
     * 
     */
    public AutomationType createAutomationType() {
        return new AutomationType();
    }

    /**
     * Create an instance of {@link PannerShellType }
     * 
     */
    public PannerShellType createPannerShellType() {
        return new PannerShellType();
    }

    /**
     * Create an instance of {@link WindowType }
     * 
     */
    public WindowType createWindowType() {
        return new WindowType();
    }

    /**
     * Create an instance of {@link PortType }
     * 
     */
    public PortType createPortType() {
        return new PortType();
    }

    /**
     * Create an instance of {@link FadeOutType }
     * 
     */
    public FadeOutType createFadeOutType() {
        return new FadeOutType();
    }

    /**
     * Create an instance of {@link RegionType }
     * 
     */
    public RegionType createRegionType() {
        return new RegionType();
    }

    /**
     * Create an instance of {@link ProcessorType }
     * 
     */
    public ProcessorType createProcessorType() {
        return new ProcessorType();
    }

    /**
     * Create an instance of {@link MeterType }
     * 
     */
    public MeterType createMeterType() {
        return new MeterType();
    }

    /**
     * Create an instance of {@link SpeakersType }
     * 
     */
    public SpeakersType createSpeakersType() {
        return new SpeakersType();
    }

    /**
     * Create an instance of {@link WindowsVstType }
     * 
     */
    public WindowsVstType createWindowsVstType() {
        return new WindowsVstType();
    }

    /**
     * Create an instance of {@link ChannelsType }
     * 
     */
    public ChannelsType createChannelsType() {
        return new ChannelsType();
    }

    /**
     * Create an instance of {@link PlaylistsType }
     * 
     */
    public PlaylistsType createPlaylistsType() {
        return new PlaylistsType();
    }

    /**
     * Create an instance of {@link LTCOutType }
     * 
     */
    public LTCOutType createLTCOutType() {
        return new LTCOutType();
    }

    /**
     * Create an instance of {@link MuteMasterType }
     * 
     */
    public MuteMasterType createMuteMasterType() {
        return new MuteMasterType();
    }

    /**
     * Create an instance of {@link TempoMapType }
     * 
     */
    public TempoMapType createTempoMapType() {
        return new TempoMapType();
    }

    /**
     * Create an instance of {@link ExportFilenameType }
     * 
     */
    public ExportFilenameType createExportFilenameType() {
        return new ExportFilenameType();
    }

    /**
     * Create an instance of {@link StripableAutomationControlType }
     * 
     */
    public StripableAutomationControlType createStripableAutomationControlType() {
        return new StripableAutomationControlType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link RangeType }
     * 
     */
    public RangeType createRangeType() {
        return new RangeType();
    }

    /**
     * Create an instance of {@link ExportChannelConfigurationType }
     * 
     */
    public ExportChannelConfigurationType createExportChannelConfigurationType() {
        return new ExportChannelConfigurationType();
    }

    /**
     * Create an instance of {@link SelectionType }
     * 
     */
    public SelectionType createSelectionType() {
        return new SelectionType();
    }

    /**
     * Create an instance of {@link UIType }
     * 
     */
    public UIType createUIType() {
        return new UIType();
    }

    /**
     * Create an instance of {@link AutomationListType }
     * 
     */
    public AutomationListType createAutomationListType() {
        return new AutomationListType();
    }

    /**
     * Create an instance of {@link PannableType }
     * 
     */
    public PannableType createPannableType() {
        return new PannableType();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersType createParametersType() {
        return new ParametersType();
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

    /**
     * Create an instance of {@link TempoType }
     * 
     */
    public TempoType createTempoType() {
        return new TempoType();
    }

    /**
     * Create an instance of {@link ScriptType }
     * 
     */
    public ScriptType createScriptType() {
        return new ScriptType();
    }

    /**
     * Create an instance of {@link ConfiguredOutputType }
     * 
     */
    public ConfiguredOutputType createConfiguredOutputType() {
        return new ConfiguredOutputType();
    }

    /**
     * Create an instance of {@link EnvelopeType }
     * 
     */
    public EnvelopeType createEnvelopeType() {
        return new EnvelopeType();
    }

    /**
     * Create an instance of {@link ExportRevisionType }
     * 
     */
    public ExportRevisionType createExportRevisionType() {
        return new ExportRevisionType();
    }

    /**
     * Create an instance of {@link ProgramVersionType }
     * 
     */
    public ProgramVersionType createProgramVersionType() {
        return new ProgramVersionType();
    }

    /**
     * Create an instance of {@link ExportTimespanType }
     * 
     */
    public ExportTimespanType createExportTimespanType() {
        return new ExportTimespanType();
    }

    /**
     * Create an instance of {@link GUIObjectStateType }
     * 
     */
    public GUIObjectStateType createGUIObjectStateType() {
        return new GUIObjectStateType();
    }

    /**
     * Create an instance of {@link FieldType }
     * 
     */
    public FieldType createFieldType() {
        return new FieldType();
    }

    /**
     * Create an instance of {@link ProtocolType }
     * 
     */
    public ProtocolType createProtocolType() {
        return new ProtocolType();
    }

    /**
     * Create an instance of {@link MIDIPortsType }
     * 
     */
    public MIDIPortsType createMIDIPortsType() {
        return new MIDIPortsType();
    }

    /**
     * Create an instance of {@link VideomonitorType }
     * 
     */
    public VideomonitorType createVideomonitorType() {
        return new VideomonitorType();
    }

    /**
     * Create an instance of {@link InverseFadeInType }
     * 
     */
    public InverseFadeInType createInverseFadeInType() {
        return new InverseFadeInType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link ChannelType }
     * 
     */
    public ChannelType createChannelType() {
        return new ChannelType();
    }

    /**
     * Create an instance of {@link RouteType.Slavable }
     * 
     */
    public RouteType.Slavable createRouteTypeSlavable() {
        return new RouteType.Slavable();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SessionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Session")
    public JAXBElement<SessionType> createSession(SessionType value) {
        return new JAXBElement<SessionType>(_Session_QNAME, SessionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InverseFadeInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InverseFadeIn", scope = RegionType.class)
    public JAXBElement<InverseFadeInType> createRegionTypeInverseFadeIn(InverseFadeInType value) {
        return new JAXBElement<InverseFadeInType>(_RegionTypeInverseFadeIn_QNAME, InverseFadeInType.class, RegionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FadeInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FadeIn", scope = RegionType.class)
    public JAXBElement<FadeInType> createRegionTypeFadeIn(FadeInType value) {
        return new JAXBElement<FadeInType>(_RegionTypeFadeIn_QNAME, FadeInType.class, RegionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FadeOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FadeOut", scope = RegionType.class)
    public JAXBElement<FadeOutType> createRegionTypeFadeOut(FadeOutType value) {
        return new JAXBElement<FadeOutType>(_RegionTypeFadeOut_QNAME, FadeOutType.class, RegionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InverseFadeOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InverseFadeOut", scope = RegionType.class)
    public JAXBElement<InverseFadeOutType> createRegionTypeInverseFadeOut(InverseFadeOutType value) {
        return new JAXBElement<InverseFadeOutType>(_RegionTypeInverseFadeOut_QNAME, InverseFadeOutType.class, RegionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvelopeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Envelope", scope = RegionType.class)
    public JAXBElement<EnvelopeType> createRegionTypeEnvelope(EnvelopeType value) {
        return new JAXBElement<EnvelopeType>(_RegionTypeEnvelope_QNAME, EnvelopeType.class, RegionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Region", scope = PlaylistType.class)
    public JAXBElement<RegionType> createPlaylistTypeRegion(RegionType value) {
        return new JAXBElement<RegionType>(_PlaylistTypeRegion_QNAME, RegionType.class, PlaylistType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Port", scope = ChannelType.class)
    public JAXBElement<PortType> createChannelTypePort(PortType value) {
        return new JAXBElement<PortType>(_ChannelTypePort_QNAME, PortType.class, ChannelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PannableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pannable", scope = ProcessorType.class)
    public JAXBElement<PannableType> createProcessorTypePannable(PannableType value) {
        return new JAXBElement<PannableType>(_ProcessorTypePannable_QNAME, PannableType.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputMap0Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutputMap-0", scope = ProcessorType.class)
    public JAXBElement<OutputMap0Type> createProcessorTypeOutputMap0(OutputMap0Type value) {
        return new JAXBElement<OutputMap0Type>(_ProcessorTypeOutputMap0_QNAME, OutputMap0Type.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AutomationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Automation", scope = ProcessorType.class)
    public JAXBElement<AutomationType> createProcessorTypeAutomation(AutomationType value) {
        return new JAXBElement<AutomationType>(_ProcessorTypeAutomation_QNAME, AutomationType.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PresetOutput", scope = ProcessorType.class)
    public JAXBElement<String> createProcessorTypePresetOutput(String value) {
        return new JAXBElement<String>(_ProcessorTypePresetOutput_QNAME, String.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControllableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Controllable", scope = ProcessorType.class)
    public JAXBElement<ControllableType> createProcessorTypeControllable(ControllableType value) {
        return new JAXBElement<ControllableType>(_ProcessorTypeControllable_QNAME, ControllableType.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ThruMap", scope = ProcessorType.class)
    public JAXBElement<String> createProcessorTypeThruMap(String value) {
        return new JAXBElement<String>(_ProcessorTypeThruMap_QNAME, String.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PannerShellType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PannerShell", scope = ProcessorType.class)
    public JAXBElement<PannerShellType> createProcessorTypePannerShell(PannerShellType value) {
        return new JAXBElement<PannerShellType>(_ProcessorTypePannerShell_QNAME, PannerShellType.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomSinksType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomSinks", scope = ProcessorType.class)
    public JAXBElement<CustomSinksType> createProcessorTypeCustomSinks(CustomSinksType value) {
        return new JAXBElement<CustomSinksType>(_ProcessorTypeCustomSinks_QNAME, CustomSinksType.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfiguredOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConfiguredOutput", scope = ProcessorType.class)
    public JAXBElement<ConfiguredOutputType> createProcessorTypeConfiguredOutput(ConfiguredOutputType value) {
        return new JAXBElement<ConfiguredOutputType>(_ProcessorTypeConfiguredOutput_QNAME, ConfiguredOutputType.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputMap0Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InputMap-0", scope = ProcessorType.class)
    public JAXBElement<InputMap0Type> createProcessorTypeInputMap0(InputMap0Type value) {
        return new JAXBElement<InputMap0Type>(_ProcessorTypeInputMap0_QNAME, InputMap0Type.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WindowsVstType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "windows-vst", scope = ProcessorType.class)
    public JAXBElement<WindowsVstType> createProcessorTypeWindowsVst(WindowsVstType value) {
        return new JAXBElement<WindowsVstType>(_ProcessorTypeWindowsVst_QNAME, WindowsVstType.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfiguredInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConfiguredInput", scope = ProcessorType.class)
    public JAXBElement<ConfiguredInputType> createProcessorTypeConfiguredInput(ConfiguredInputType value) {
        return new JAXBElement<ConfiguredInputType>(_ProcessorTypeConfiguredInput_QNAME, ConfiguredInputType.class, ProcessorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Connection", scope = PortType.class)
    public JAXBElement<ConnectionType> createPortTypeConnection(ConnectionType value) {
        return new JAXBElement<ConnectionType>(_PortTypeConnection_QNAME, ConnectionType.class, PortType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "events", scope = AutomationListType.class)
    public JAXBElement<String> createAutomationListTypeEvents(String value) {
        return new JAXBElement<String>(_AutomationListTypeEvents_QNAME, String.class, AutomationListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelmapType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Channelmap", scope = InputMap0Type.class)
    public JAXBElement<ChannelmapType> createInputMap0TypeChannelmap(ChannelmapType value) {
        return new JAXBElement<ChannelmapType>(_InputMap0TypeChannelmap_QNAME, ChannelmapType.class, InputMap0Type.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Object", scope = ObjectType.class)
    public JAXBElement<ObjectType> createObjectTypeObject(ObjectType value) {
        return new JAXBElement<ObjectType>(_ObjectTypeObject_QNAME, ObjectType.class, ObjectType.class, value);
    }

}
