//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Object" type="{}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="strip-width" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="midnam-model-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="midnam-custom-device-mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="color-mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="note-range-min" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="note-range-max" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectType", propOrder = {
    "content"
})
public class ObjectType {

    @XmlElementRef(name = "Object", type = JAXBElement.class, required = false)
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "height")
    protected Short height;
    @XmlAttribute(name = "visible")
    protected Byte visible;
    @XmlAttribute(name = "strip-width")
    protected String stripWidth;
    @XmlAttribute(name = "midnam-model-name")
    protected String midnamModelName;
    @XmlAttribute(name = "midnam-custom-device-mode")
    protected String midnamCustomDeviceMode;
    @XmlAttribute(name = "color-mode")
    protected String colorMode;
    @XmlAttribute(name = "note-range-min")
    protected Byte noteRangeMin;
    @XmlAttribute(name = "note-range-max")
    protected Byte noteRangeMax;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ObjectType }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setHeight(Short value) {
        this.height = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setVisible(Byte value) {
        this.visible = value;
    }

    /**
     * Gets the value of the stripWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStripWidth() {
        return stripWidth;
    }

    /**
     * Sets the value of the stripWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStripWidth(String value) {
        this.stripWidth = value;
    }

    /**
     * Gets the value of the midnamModelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMidnamModelName() {
        return midnamModelName;
    }

    /**
     * Sets the value of the midnamModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMidnamModelName(String value) {
        this.midnamModelName = value;
    }

    /**
     * Gets the value of the midnamCustomDeviceMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMidnamCustomDeviceMode() {
        return midnamCustomDeviceMode;
    }

    /**
     * Sets the value of the midnamCustomDeviceMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMidnamCustomDeviceMode(String value) {
        this.midnamCustomDeviceMode = value;
    }

    /**
     * Gets the value of the colorMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorMode() {
        return colorMode;
    }

    /**
     * Sets the value of the colorMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorMode(String value) {
        this.colorMode = value;
    }

    /**
     * Gets the value of the noteRangeMin property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getNoteRangeMin() {
        return noteRangeMin;
    }

    /**
     * Sets the value of the noteRangeMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNoteRangeMin(Byte value) {
        this.noteRangeMin = value;
    }

    /**
     * Gets the value of the noteRangeMax property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getNoteRangeMax() {
        return noteRangeMax;
    }

    /**
     * Sets the value of the noteRangeMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNoteRangeMax(Byte value) {
        this.noteRangeMax = value;
    }

}
