//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for PannerShellType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PannerShellType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="bypassed" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="user-panner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="linked-to-route" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PannerShellType", propOrder = {
    "value"
})
public class PannerShellType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "bypassed")
    protected Byte bypassed;
    @XmlAttribute(name = "user-panner")
    protected String userPanner;
    @XmlAttribute(name = "linked-to-route")
    protected Byte linkedToRoute;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the bypassed property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getBypassed() {
        return bypassed;
    }

    /**
     * Sets the value of the bypassed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setBypassed(Byte value) {
        this.bypassed = value;
    }

    /**
     * Gets the value of the userPanner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserPanner() {
        return userPanner;
    }

    /**
     * Sets the value of the userPanner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserPanner(String value) {
        this.userPanner = value;
    }

    /**
     * Gets the value of the linkedToRoute property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getLinkedToRoute() {
        return linkedToRoute;
    }

    /**
     * Sets the value of the linkedToRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setLinkedToRoute(Byte value) {
        this.linkedToRoute = value;
    }

}
