//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for parametersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parametersType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="param-0" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="param-1" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="param-2" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="param-3" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="param-4" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="param-5" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="param-6" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="param-7" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="param-8" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="param-9" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="param-10" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="param-11" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="param-12" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="param-13" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="param-14" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parametersType", propOrder = {
    "value"
})
public class ParametersType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "param-0")
    protected Float param0;
    @XmlAttribute(name = "param-1")
    protected Float param1;
    @XmlAttribute(name = "param-2")
    protected Float param2;
    @XmlAttribute(name = "param-3")
    protected Byte param3;
    @XmlAttribute(name = "param-4")
    protected Byte param4;
    @XmlAttribute(name = "param-5")
    protected Byte param5;
    @XmlAttribute(name = "param-6")
    protected Byte param6;
    @XmlAttribute(name = "param-7")
    protected Byte param7;
    @XmlAttribute(name = "param-8")
    protected Float param8;
    @XmlAttribute(name = "param-9")
    protected Float param9;
    @XmlAttribute(name = "param-10")
    protected Float param10;
    @XmlAttribute(name = "param-11")
    protected Byte param11;
    @XmlAttribute(name = "param-12")
    protected Float param12;
    @XmlAttribute(name = "param-13")
    protected Float param13;
    @XmlAttribute(name = "param-14")
    protected Float param14;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the param0 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam0() {
        return param0;
    }

    /**
     * Sets the value of the param0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam0(Float value) {
        this.param0 = value;
    }

    /**
     * Gets the value of the param1 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam1() {
        return param1;
    }

    /**
     * Sets the value of the param1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam1(Float value) {
        this.param1 = value;
    }

    /**
     * Gets the value of the param2 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam2() {
        return param2;
    }

    /**
     * Sets the value of the param2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam2(Float value) {
        this.param2 = value;
    }

    /**
     * Gets the value of the param3 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getParam3() {
        return param3;
    }

    /**
     * Sets the value of the param3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setParam3(Byte value) {
        this.param3 = value;
    }

    /**
     * Gets the value of the param4 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getParam4() {
        return param4;
    }

    /**
     * Sets the value of the param4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setParam4(Byte value) {
        this.param4 = value;
    }

    /**
     * Gets the value of the param5 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getParam5() {
        return param5;
    }

    /**
     * Sets the value of the param5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setParam5(Byte value) {
        this.param5 = value;
    }

    /**
     * Gets the value of the param6 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getParam6() {
        return param6;
    }

    /**
     * Sets the value of the param6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setParam6(Byte value) {
        this.param6 = value;
    }

    /**
     * Gets the value of the param7 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getParam7() {
        return param7;
    }

    /**
     * Sets the value of the param7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setParam7(Byte value) {
        this.param7 = value;
    }

    /**
     * Gets the value of the param8 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam8() {
        return param8;
    }

    /**
     * Sets the value of the param8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam8(Float value) {
        this.param8 = value;
    }

    /**
     * Gets the value of the param9 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam9() {
        return param9;
    }

    /**
     * Sets the value of the param9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam9(Float value) {
        this.param9 = value;
    }

    /**
     * Gets the value of the param10 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam10() {
        return param10;
    }

    /**
     * Sets the value of the param10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam10(Float value) {
        this.param10 = value;
    }

    /**
     * Gets the value of the param11 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getParam11() {
        return param11;
    }

    /**
     * Sets the value of the param11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setParam11(Byte value) {
        this.param11 = value;
    }

    /**
     * Gets the value of the param12 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam12() {
        return param12;
    }

    /**
     * Sets the value of the param12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam12(Float value) {
        this.param12 = value;
    }

    /**
     * Gets the value of the param13 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam13() {
        return param13;
    }

    /**
     * Sets the value of the param13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam13(Float value) {
        this.param13 = value;
    }

    /**
     * Gets the value of the param14 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getParam14() {
        return param14;
    }

    /**
     * Sets the value of the param14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setParam14(Float value) {
        this.param14 = value;
    }

}
