//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Automation" type="{}AutomationType" minOccurs="0"/>
 *         &lt;element name="ConfiguredInput" type="{}ConfiguredInputType" minOccurs="0"/>
 *         &lt;element name="CustomSinks" type="{}CustomSinksType" minOccurs="0"/>
 *         &lt;element name="ConfiguredOutput" type="{}ConfiguredOutputType" minOccurs="0"/>
 *         &lt;element name="PresetOutput" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InputMap-0" type="{}InputMap-0Type" minOccurs="0"/>
 *         &lt;element name="OutputMap-0" type="{}OutputMap-0Type" minOccurs="0"/>
 *         &lt;element name="ThruMap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="windows-vst" type="{}windows-vstType" minOccurs="0"/>
 *         &lt;element name="Controllable" type="{}ControllableType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PannerShell" type="{}PannerShellType" minOccurs="0"/>
 *         &lt;element name="Pannable" type="{}PannableType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="user-latency" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="own-input" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="own-output" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="output" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="unique-id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="custom" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessorType", propOrder = {
    "content"
})
public class ProcessorType {

    @XmlElementRefs({
        @XmlElementRef(name = "windows-vst", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CustomSinks", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Pannable", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ConfiguredInput", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ThruMap", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PannerShell", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ConfiguredOutput", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "InputMap-0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OutputMap-0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Automation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PresetOutput", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Controllable", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "id")
    protected Short id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "active")
    protected Byte active;
    @XmlAttribute(name = "user-latency")
    protected Byte userLatency;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "own-input")
    protected Byte ownInput;
    @XmlAttribute(name = "own-output")
    protected Byte ownOutput;
    @XmlAttribute(name = "output")
    protected String output;
    @XmlAttribute(name = "role")
    protected String role;
    @XmlAttribute(name = "unique-id")
    protected Integer uniqueId;
    @XmlAttribute(name = "count")
    protected Byte count;
    @XmlAttribute(name = "custom")
    protected Byte custom;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PannableType }{@code >}
     * {@link JAXBElement }{@code <}{@link PannerShellType }{@code >}
     * {@link JAXBElement }{@code <}{@link InputMap0Type }{@code >}
     * {@link JAXBElement }{@code <}{@link OutputMap0Type }{@code >}
     * {@link JAXBElement }{@code <}{@link AutomationType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ControllableType }{@code >}
     * {@link JAXBElement }{@code <}{@link WindowsVstType }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link CustomSinksType }{@code >}
     * {@link JAXBElement }{@code <}{@link ConfiguredInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ConfiguredOutputType }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setId(Short value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setActive(Byte value) {
        this.active = value;
    }

    /**
     * Gets the value of the userLatency property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getUserLatency() {
        return userLatency;
    }

    /**
     * Sets the value of the userLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setUserLatency(Byte value) {
        this.userLatency = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the ownInput property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getOwnInput() {
        return ownInput;
    }

    /**
     * Sets the value of the ownInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setOwnInput(Byte value) {
        this.ownInput = value;
    }

    /**
     * Gets the value of the ownOutput property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getOwnOutput() {
        return ownOutput;
    }

    /**
     * Sets the value of the ownOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setOwnOutput(Byte value) {
        this.ownOutput = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutput(String value) {
        this.output = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the uniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUniqueId() {
        return uniqueId;
    }

    /**
     * Sets the value of the uniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUniqueId(Integer value) {
        this.uniqueId = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCount(Byte value) {
        this.count = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCustom(Byte value) {
        this.custom = value;
    }

}
