//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for RouteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="PresentationInfo" type="{}PresentationInfoType"/>
 *         &lt;element name="Controllable" type="{}ControllableType"/>
 *         &lt;element name="IO" type="{}IOType"/>
 *         &lt;element name="MuteMaster" type="{}MuteMasterType"/>
 *         &lt;element name="Automation" type="{}AutomationType"/>
 *         &lt;element name="Pannable" type="{}PannableType"/>
 *         &lt;element name="Processor" type="{}ProcessorType"/>
 *         &lt;element name="Slavable">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="flags" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="self-solo" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="soloed-by-upstream" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="soloed-by-downstream" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="solo-isolated" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="solo-safe" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="phase-invert" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="monitoring" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="parameter" type="{http://www.w3.org/2001/XMLSchema}short" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Diskstream" type="{}DiskstreamType"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="default-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="strict-io" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="denormal-protection" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="meter-point" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="meter-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="saved-meter-point" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="playback-channel-mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="capture-channel-mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="playback-channel-mask" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="capture-channel-mask" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="note-mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="step-editing" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="input-active" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteType", propOrder = {
    "presentationInfoOrControllableOrIO"
})
public class RouteType {

    @XmlElements({
        @XmlElement(name = "PresentationInfo", type = PresentationInfoType.class),
        @XmlElement(name = "Controllable", type = ControllableType.class),
        @XmlElement(name = "IO", type = IOType.class),
        @XmlElement(name = "MuteMaster", type = MuteMasterType.class),
        @XmlElement(name = "Automation", type = AutomationType.class),
        @XmlElement(name = "Pannable", type = PannableType.class),
        @XmlElement(name = "Processor", type = ProcessorType.class),
        @XmlElement(name = "Slavable", type = RouteType.Slavable.class),
        @XmlElement(name = "Diskstream", type = DiskstreamType.class)
    })
    protected List<Object> presentationInfoOrControllableOrIO;
    @XmlAttribute(name = "id")
    protected Short id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "default-type")
    protected String defaultType;
    @XmlAttribute(name = "strict-io")
    protected Byte strictIo;
    @XmlAttribute(name = "active")
    protected Byte active;
    @XmlAttribute(name = "denormal-protection")
    protected Byte denormalProtection;
    @XmlAttribute(name = "meter-point")
    protected String meterPoint;
    @XmlAttribute(name = "meter-type")
    protected String meterType;
    @XmlAttribute(name = "saved-meter-point")
    protected String savedMeterPoint;
    @XmlAttribute(name = "mode")
    protected String mode;
    @XmlAttribute(name = "playback-channel-mode")
    protected String playbackChannelMode;
    @XmlAttribute(name = "capture-channel-mode")
    protected String captureChannelMode;
    @XmlAttribute(name = "playback-channel-mask")
    protected String playbackChannelMask;
    @XmlAttribute(name = "capture-channel-mask")
    protected String captureChannelMask;
    @XmlAttribute(name = "note-mode")
    protected String noteMode;
    @XmlAttribute(name = "step-editing")
    protected Byte stepEditing;
    @XmlAttribute(name = "input-active")
    protected Byte inputActive;

    /**
     * Gets the value of the presentationInfoOrControllableOrIO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentationInfoOrControllableOrIO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentationInfoOrControllableOrIO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PresentationInfoType }
     * {@link ControllableType }
     * {@link IOType }
     * {@link MuteMasterType }
     * {@link AutomationType }
     * {@link PannableType }
     * {@link ProcessorType }
     * {@link RouteType.Slavable }
     * {@link DiskstreamType }
     * 
     * 
     */
    public List<Object> getPresentationInfoOrControllableOrIO() {
        if (presentationInfoOrControllableOrIO == null) {
            presentationInfoOrControllableOrIO = new ArrayList<Object>();
        }
        return this.presentationInfoOrControllableOrIO;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setId(Short value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the defaultType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultType() {
        return defaultType;
    }

    /**
     * Sets the value of the defaultType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultType(String value) {
        this.defaultType = value;
    }

    /**
     * Gets the value of the strictIo property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getStrictIo() {
        return strictIo;
    }

    /**
     * Sets the value of the strictIo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setStrictIo(Byte value) {
        this.strictIo = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setActive(Byte value) {
        this.active = value;
    }

    /**
     * Gets the value of the denormalProtection property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getDenormalProtection() {
        return denormalProtection;
    }

    /**
     * Sets the value of the denormalProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setDenormalProtection(Byte value) {
        this.denormalProtection = value;
    }

    /**
     * Gets the value of the meterPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterPoint() {
        return meterPoint;
    }

    /**
     * Sets the value of the meterPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterPoint(String value) {
        this.meterPoint = value;
    }

    /**
     * Gets the value of the meterType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterType() {
        return meterType;
    }

    /**
     * Sets the value of the meterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterType(String value) {
        this.meterType = value;
    }

    /**
     * Gets the value of the savedMeterPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSavedMeterPoint() {
        return savedMeterPoint;
    }

    /**
     * Sets the value of the savedMeterPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSavedMeterPoint(String value) {
        this.savedMeterPoint = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the playbackChannelMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaybackChannelMode() {
        return playbackChannelMode;
    }

    /**
     * Sets the value of the playbackChannelMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaybackChannelMode(String value) {
        this.playbackChannelMode = value;
    }

    /**
     * Gets the value of the captureChannelMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptureChannelMode() {
        return captureChannelMode;
    }

    /**
     * Sets the value of the captureChannelMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptureChannelMode(String value) {
        this.captureChannelMode = value;
    }

    /**
     * Gets the value of the playbackChannelMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaybackChannelMask() {
        return playbackChannelMask;
    }

    /**
     * Sets the value of the playbackChannelMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaybackChannelMask(String value) {
        this.playbackChannelMask = value;
    }

    /**
     * Gets the value of the captureChannelMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptureChannelMask() {
        return captureChannelMask;
    }

    /**
     * Sets the value of the captureChannelMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptureChannelMask(String value) {
        this.captureChannelMask = value;
    }

    /**
     * Gets the value of the noteMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteMode() {
        return noteMode;
    }

    /**
     * Sets the value of the noteMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteMode(String value) {
        this.noteMode = value;
    }

    /**
     * Gets the value of the stepEditing property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getStepEditing() {
        return stepEditing;
    }

    /**
     * Sets the value of the stepEditing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setStepEditing(Byte value) {
        this.stepEditing = value;
    }

    /**
     * Gets the value of the inputActive property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getInputActive() {
        return inputActive;
    }

    /**
     * Sets the value of the inputActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setInputActive(Byte value) {
        this.inputActive = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="flags" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="self-solo" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="soloed-by-upstream" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="soloed-by-downstream" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="solo-isolated" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="solo-safe" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="phase-invert" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="monitoring" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="parameter" type="{http://www.w3.org/2001/XMLSchema}short" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Slavable {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "id")
        protected Short id;
        @XmlAttribute(name = "flags")
        protected String flags;
        @XmlAttribute(name = "value")
        protected Float valueAttribute;
        @XmlAttribute(name = "self-solo")
        protected Byte selfSolo;
        @XmlAttribute(name = "soloed-by-upstream")
        protected Byte soloedByUpstream;
        @XmlAttribute(name = "soloed-by-downstream")
        protected Byte soloedByDownstream;
        @XmlAttribute(name = "solo-isolated")
        protected Byte soloIsolated;
        @XmlAttribute(name = "solo-safe")
        protected Byte soloSafe;
        @XmlAttribute(name = "phase-invert")
        protected String phaseInvert;
        @XmlAttribute(name = "monitoring")
        protected String monitoring;
        @XmlAttribute(name = "parameter")
        protected Short parameter;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setId(Short value) {
            this.id = value;
        }

        /**
         * Gets the value of the flags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFlags() {
            return flags;
        }

        /**
         * Sets the value of the flags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFlags(String value) {
            this.flags = value;
        }

        /**
         * Gets the value of the valueAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getValueAttribute() {
            return valueAttribute;
        }

        /**
         * Sets the value of the valueAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setValueAttribute(Float value) {
            this.valueAttribute = value;
        }

        /**
         * Gets the value of the selfSolo property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSelfSolo() {
            return selfSolo;
        }

        /**
         * Sets the value of the selfSolo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSelfSolo(Byte value) {
            this.selfSolo = value;
        }

        /**
         * Gets the value of the soloedByUpstream property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSoloedByUpstream() {
            return soloedByUpstream;
        }

        /**
         * Sets the value of the soloedByUpstream property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSoloedByUpstream(Byte value) {
            this.soloedByUpstream = value;
        }

        /**
         * Gets the value of the soloedByDownstream property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSoloedByDownstream() {
            return soloedByDownstream;
        }

        /**
         * Sets the value of the soloedByDownstream property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSoloedByDownstream(Byte value) {
            this.soloedByDownstream = value;
        }

        /**
         * Gets the value of the soloIsolated property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSoloIsolated() {
            return soloIsolated;
        }

        /**
         * Sets the value of the soloIsolated property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSoloIsolated(Byte value) {
            this.soloIsolated = value;
        }

        /**
         * Gets the value of the soloSafe property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSoloSafe() {
            return soloSafe;
        }

        /**
         * Sets the value of the soloSafe property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSoloSafe(Byte value) {
            this.soloSafe = value;
        }

        /**
         * Gets the value of the phaseInvert property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhaseInvert() {
            return phaseInvert;
        }

        /**
         * Sets the value of the phaseInvert property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhaseInvert(String value) {
            this.phaseInvert = value;
        }

        /**
         * Gets the value of the monitoring property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonitoring() {
            return monitoring;
        }

        /**
         * Sets the value of the monitoring property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonitoring(String value) {
            this.monitoring = value;
        }

        /**
         * Gets the value of the parameter property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getParameter() {
            return parameter;
        }

        /**
         * Sets the value of the parameter property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setParameter(Short value) {
            this.parameter = value;
        }

    }

}
