//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for StripableAutomationControlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StripableAutomationControlType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="stripable" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="control" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StripableAutomationControlType", propOrder = {
    "value"
})
public class StripableAutomationControlType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "stripable")
    protected Short stripable;
    @XmlAttribute(name = "control")
    protected Byte control;
    @XmlAttribute(name = "order")
    protected Byte order;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the stripable property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getStripable() {
        return stripable;
    }

    /**
     * Sets the value of the stripable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setStripable(Short value) {
        this.stripable = value;
    }

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setControl(Byte value) {
        this.control = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setOrder(Byte value) {
        this.order = value;
    }

}
