//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TempoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TempoType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="pulse" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="frame" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="movable" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="lock-style" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beats-per-minute" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="note-type" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="clamped" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="end-beats-per-minute" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="locked-to-meter" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TempoType", propOrder = {
    "value"
})
public class TempoType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "pulse")
    protected Byte pulse;
    @XmlAttribute(name = "frame")
    protected Byte frame;
    @XmlAttribute(name = "movable")
    protected Byte movable;
    @XmlAttribute(name = "lock-style")
    protected String lockStyle;
    @XmlAttribute(name = "beats-per-minute")
    protected Byte beatsPerMinute;
    @XmlAttribute(name = "note-type")
    protected Byte noteType;
    @XmlAttribute(name = "clamped")
    protected Byte clamped;
    @XmlAttribute(name = "end-beats-per-minute")
    protected Short endBeatsPerMinute;
    @XmlAttribute(name = "active")
    protected Byte active;
    @XmlAttribute(name = "locked-to-meter")
    protected Byte lockedToMeter;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the pulse property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPulse() {
        return pulse;
    }

    /**
     * Sets the value of the pulse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPulse(Byte value) {
        this.pulse = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFrame(Byte value) {
        this.frame = value;
    }

    /**
     * Gets the value of the movable property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMovable() {
        return movable;
    }

    /**
     * Sets the value of the movable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMovable(Byte value) {
        this.movable = value;
    }

    /**
     * Gets the value of the lockStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockStyle() {
        return lockStyle;
    }

    /**
     * Sets the value of the lockStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockStyle(String value) {
        this.lockStyle = value;
    }

    /**
     * Gets the value of the beatsPerMinute property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getBeatsPerMinute() {
        return beatsPerMinute;
    }

    /**
     * Sets the value of the beatsPerMinute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setBeatsPerMinute(Byte value) {
        this.beatsPerMinute = value;
    }

    /**
     * Gets the value of the noteType property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getNoteType() {
        return noteType;
    }

    /**
     * Sets the value of the noteType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNoteType(Byte value) {
        this.noteType = value;
    }

    /**
     * Gets the value of the clamped property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getClamped() {
        return clamped;
    }

    /**
     * Sets the value of the clamped property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setClamped(Byte value) {
        this.clamped = value;
    }

    /**
     * Gets the value of the endBeatsPerMinute property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEndBeatsPerMinute() {
        return endBeatsPerMinute;
    }

    /**
     * Sets the value of the endBeatsPerMinute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEndBeatsPerMinute(Short value) {
        this.endBeatsPerMinute = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setActive(Byte value) {
        this.active = value;
    }

    /**
     * Gets the value of the lockedToMeter property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getLockedToMeter() {
        return lockedToMeter;
    }

    /**
     * Sets the value of the lockedToMeter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setLockedToMeter(Byte value) {
        this.lockedToMeter = value;
    }

}
