//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Window" type="{}WindowType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GUIObjectState" type="{}GUIObjectStateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIType", propOrder = {
    "window",
    "guiObjectState"
})
public class UIType {

    @XmlElement(name = "Window")
    protected List<WindowType> window;
    @XmlElement(name = "GUIObjectState", required = true)
    protected GUIObjectStateType guiObjectState;

    /**
     * Gets the value of the window property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the window property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWindow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WindowType }
     * 
     * 
     */
    public List<WindowType> getWindow() {
        if (window == null) {
            window = new ArrayList<WindowType>();
        }
        return this.window;
    }

    /**
     * Gets the value of the guiObjectState property.
     * 
     * @return
     *     possible object is
     *     {@link GUIObjectStateType }
     *     
     */
    public GUIObjectStateType getGUIObjectState() {
        return guiObjectState;
    }

    /**
     * Sets the value of the guiObjectState property.
     * 
     * @param value
     *     allowed object is
     *     {@link GUIObjectStateType }
     *     
     */
    public void setGUIObjectState(GUIObjectStateType value) {
        this.guiObjectState = value;
    }

}
