//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 11:42:00 PM CEST 
//


package org.codingspiderfox.ardoursessionparser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for WindowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindowType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="x-off" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="y-off" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="x-size" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="y-size" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="custom-ui" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindowType", propOrder = {
    "value"
})
public class WindowType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "visible")
    protected Byte visible;
    @XmlAttribute(name = "x-off")
    protected Short xOff;
    @XmlAttribute(name = "y-off")
    protected Short yOff;
    @XmlAttribute(name = "x-size")
    protected Short xSize;
    @XmlAttribute(name = "y-size")
    protected Short ySize;
    @XmlAttribute(name = "custom-ui")
    protected Byte customUi;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setVisible(Byte value) {
        this.visible = value;
    }

    /**
     * Gets the value of the xOff property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getXOff() {
        return xOff;
    }

    /**
     * Sets the value of the xOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setXOff(Short value) {
        this.xOff = value;
    }

    /**
     * Gets the value of the yOff property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getYOff() {
        return yOff;
    }

    /**
     * Sets the value of the yOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setYOff(Short value) {
        this.yOff = value;
    }

    /**
     * Gets the value of the xSize property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getXSize() {
        return xSize;
    }

    /**
     * Sets the value of the xSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setXSize(Short value) {
        this.xSize = value;
    }

    /**
     * Gets the value of the ySize property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getYSize() {
        return ySize;
    }

    /**
     * Sets the value of the ySize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setYSize(Short value) {
        this.ySize = value;
    }

    /**
     * Gets the value of the customUi property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCustomUi() {
        return customUi;
    }

    /**
     * Sets the value of the customUi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCustomUi(Byte value) {
        this.customUi = value;
    }

}
